### ISSUE TITLE
Create quick start guide for setting up a codegen workflow inside visual studio

### ISSUE THREAD

**Issue by hippiehunter** [Synergex/HarmonyCore#10]
The sample projects use a handcrafted regen.bat and a custom menu item inside visual studio to support easily working with codegen. We need to flesh this process out and provide a simple way for users to get started using some of the templates included in this repository.

**Comment by SteveIves** [comment]
Information on doing this is now included [here](https://github.com/Synergex/HarmonyCore/wiki/Code-Generation).
