### ISSUE TITLE
Support all combinations of parameter types for structures in Traditional Bridge

### ISSUE THREAD

**Issue by hippiehunter** [Synergex/HarmonyCore#106]
This needs to include support for 
* dynamic arrays of synergy structures
* real/pseudo arrays of synergy structures
* synergy structures
* ArrayLists that contain synergy structures
* Dynamic arrays of data objects, ArrayLists of data objects,
* data objects

**Comment by shiblydangdang** [comment]
Is this available now? I'm wanting method parameters with ArrayList but they are being changed to String arrays.

**Comment by hippiehunter** [comment]
Yes we think we have support for all of the above listed parameter combinations. Can you open a new issue and provide the context around your request. 

Specifically I'm looking for the details of the following

- What is your ultimate (larger) goal
- What you're currently seeing happen
- What you would like to see happen instead
- Why you think the prior answer should be happening

Covering those questions as best as you can will allow us to answer more than just your specific question but help guide you down the most productive path. Understanding the 'why' part of your question also helps us direct our efforts in documentation and educational materials.

**Comment by shiblydangdang** [comment]
That's great thanks. I'll open a new issue asap and detail what I'm looking for etc.

**Comment by shiblydangdang** [comment]
I've just thought, we're probably not on the latest version. I'm fairly new to GitHub. How can I check what version we are using?

**Comment by shiblydangdang** [comment]
Just spotted this.....

cli-tool-versions.json

...I'll check ours asap

**Comment by shiblydangdang** [comment]
Ok. So we don't even have that file so I'm guessing we have a pretty old version!! I'll pull the latest repos and try out what I'm trying to do.

**Comment by shiblydangdang** [comment]
Can anyone point me at instructions for building this from scratch please?

**Comment by shiblydangdang** [comment]
Ignore me! I found it.

**Comment by hippiehunter** [comment]
That versions json file is for the cli tool infrastructure, it won't ever show up in your project.

You can tell what version you're on if you look in the nuget package manager at the harmony core references.

Given the age of this github issue it's unlikely that you would be on a version old enough to be missing it. I can help much more effectively if you provide the requested info from above.

**Comment by shiblydangdang** [comment]
No problem. Once I get to the point where I'm generating methods, I'll open an issue.
