### ISSUE TITLE
Add support for non-unique primary keys

### ISSUE THREAD

**Issue by hippiehunter** [Synergex/HarmonyCore#113]
The current design of the ODataController template assumes that all primary keys are unique and return a single record. This is not always the case.

We need to extend the template file to deal with non-unique primary keys and return a collection of records if necessary.

Similar logic is already used when dealing with alternate keys.

**Comment by theplasmastorm** [comment]
See https://github.com/Synergex/HarmonyCore/pull/223

**Comment by theplasmastorm** [comment]
#223 is merged in
