### ISSUE TITLE
I dont have ISMFILE.txt and a .XDL  files

### ISSUE THREAD

**Issue by hippiehunter** [Synergex/HarmonyCore#115]
From Email Support:
I need help with pointing to my data. ISM files etc. I noticed that Harmony Core seemed to require a  ISMFILE.txt and a .XDL  files? I don’t have these. I have .IS1 and .ISM records and a repository.  Why do I have to point to the actual files if using a repository? The repository .INCLUDE created a structure I don’t have? “strMYREC” I have “MYREC”.

**Comment by hippiehunter** [comment]
I think I've answered the part about txt and fdl files [here](https://github.com/Synergex/HarmonyCore/wiki/Repeatable-Unit-Tests). Essentially its used for unit tests, but its not needed if you don't turn on `ENABLE_CREATE_TEST_FILES` in your regen.bat

strMYREC should be getting included from your repository inside a DataObjectMetadataBase file. Thats not the name of the repository structure, its just the name that we are generating it for. It should use the definition 'MYREC' to create the structure in code 'strMYREC'

**Comment by Gl3nSt3wart** [comment]
Good morning Jeff,
              Thank you for those pages. That answers both of my questions.
