### ISSUE TITLE
FYI, Traditional Sample Method return Data Error 

### ISSUE THREAD

**Issue by Gl3nSt3wart** [Synergex/HarmonyCore#118]
Hello,

{Route("GetEnvironment")}  

I am using this -> https://localhost:8086/TraditionalBridge/GetEnvironment

I keep getting an Error back:
"An unhandled exception occurred while processing the request.
InvalidCastException: Unable to cast object of type 'System.String' to type 'Newtonsoft.Json.Linq.JToken'.
Services.Controllers.TraditionalBridgeService+$lc-138215764_GetEnvironment.MoveNext() in TraditionalBridgeService.dbl, line 85
"
<img width="755" alt="GetEnvironment_Error" src="https://user-images.githubusercontent.com/54644500/63953418-4b88e280-ca4f-11e9-8ff0-3530d27b3ddd.png">

**Comment by hippiehunter** [comment]
I think @SteveIves actually just fixed this in the template yesterday. It doesn't look like it's checked in yet but it should be later today. Once its checked in you'll need to replace the changed template inside your working copy.

**Comment by hippiehunter** [comment]
Slightly complicated answer to this one. We've slightly restructured the .tpl for this file to remove the 'sample' code as we felt it muddied the waters a bit when someone has generated from their own smc file. What we're going to be doing going forward is including a non generated partial class, TraditionalBridgeServiceCustom.dbl in the project template that contains the three sample methods. This makes sure that if you're using multiple interfaces you don't end up with our samples forced into each and every one of your generated services. In your case, If you take the latest .tpl files from this git repository and replace the ones in your project you will see these sample methods disappear. If you want to keep them you can create a partial class in TraditionalBridgeServiceCustom.dbl and paste them in there. 

The actual fix for the exception you're seeing is to replace the body of the method with something like this.

```
data resultTuple = await CallMethod("GetEnvironment")
mreturn (string)resultTuple.Item1
```
There have also been a few bug fixes to the Traditional Synergy side of Traditional Bridge, just like the template files the way you take updates to those is to copy the source from https://github.com/Synergex/HarmonyCore/tree/master/TraditionalBridge replacing whats in your working copy. Make sure you rebuild the project in visual studio and then you can run everything as normal.

I would normally enhance the wiki with these instructions but we're in the middle of changing how .tpl and Traditional Bridge sources are released/distributed. Let me know if anything is unclear, unhelpful or if you have additional questions.
