### ISSUE TITLE
Visual Studio 2019 not hitting Break Points in Traditional Bridge. -No symbols loaded

### ISSUE THREAD

**Issue by Gl3nSt3wart** [Synergex/HarmonyCore#121]
Hello,
I am following the pattern that is used for creating/calling methods in Traditional Bridge. I have everything running but I am unable to hit break points set in the traditional methods. Is there a setting I need? It would be helpful to step through these methods if possible. VS says "no symbols have been loaded for this document" when I hover over the break point while running.

![image](https://user-images.githubusercontent.com/54644500/65510359-c0aad480-dea2-11e9-9337-ee82d17b5a5f.png)

**Comment by Gl3nSt3wart** [comment]
Hi Steve,
Thank you for the directions. I found the launch.bat with that 4444:60 code in it. I uncommented it. Commented out the line before which was launching with dbs: here it is now->
_launch.bat_
@echo off
pushd %~dp0
setlocal
rem Set any environment required by the underlying methods
rem Configure a Synergy environment
rem call "%SYNERGYDE32%dbl\dblvars32.bat"
call "%SYNERGYDE64%dbl\dblvars64.bat"
set SFWINIPATH=D:\SYNERGY_INIT
rem Launch the host program
rem dbs TraditionalBridgeHost.dbr
rem Launch the host program for remote debugging
dbr -dv -rd 4444:60 TraditionalBridgeHost.dbr
endlocal
popd

It is TraditionalBridgehost.dbr which dispatches my method(tried to keep with the convention)
I tried to attach to the process as you described and the Synergy window came up after a minute but I got no further. Any ideas?

**Comment by SteveIves** [comment]
If you see the synergy program run after a minute it suggests that your Visual Studio “Attach” isn’t working. After the 60 second (or whatever number) timeout the process just disables debug and continues.

So focus on the Visual Studio side of things. Use a second instance of visual studio and open the TraditionalBridge project in there (so the source code is available). When you de the Debug > Attach..., make sure you are changing the drop-down option to “Synergy Telnet Based” (something like that, I’m not in front of a PC right now), and make sure you enter the DNS name or IP address followed by the port number, like this:

MyServer:4444

Other than that, it SHOULD work. Jeff and I are delivering a “Tech Day” in the UK right now, but we can help later if needed.

**Comment by Gl3nSt3wart** [comment]
Hi Steve/Jeff, unfortunately I have been unable to get the debugging to work to hit breakpoints in my traditional method. Any other suggestions?  My dev Synergy server is local to my laptop. WIth 2 instances of VS2019 Open. 1 running Harmony Core and the other with Harmony Core code open which I use to attach to process.
I have changed the method to connect from default to Synergy then it closes once I hit attach. See images.
![image](https://user-images.githubusercontent.com/54644500/65621571-05f9ff80-df92-11e9-890a-207af9286162.png)
![image](https://user-images.githubusercontent.com/54644500/65621635-1f9b4700-df92-11e9-9526-0b720c9a0c96.png)

**Comment by Gl3nSt3wart** [comment]
HI All, **Nevermind**.... I found my issue.. I have to put in MYIP:4444 and make sure as Steve said that to select Synergy telnet based in drop down.... Then it went right in... Thanks Guys!! This will help immensely with the rest of the project. 
The attach process was misleading by populating my PC name and showing me the processes.
