### ISSUE TITLE
Returning Repository data as JSON from Traditional Method

### ISSUE THREAD

**Issue by Gl3nSt3wart** [Synergex/HarmonyCore#122]
Good morning,
I have a custom traditional bridge method. I have a customer record that is in repository. Basically, I take a customer Plate and search for it in the repository record. Now I want to return all this data/maybe more as JSON.
 I am wondering if there is a built in mechanism for returning/converting this data object as JSON to my dispatcher and finally to my remote client application for display/updating.
What would be the best path here? Creating a customer class and converting that to json using a key/value pair and converting it all to a string?

**Comment by hippiehunter** [comment]
The built in mechanism for returning structrues/complex data is to generate a data object for the repository structure. For the traditional synergy side these are generated using https://github.com/Synergex/HarmonyCore/tree/master/Templates/TraditionalBridge/TraditionalMetaData.tpl & TraditionalModel.tpl 

On the .Net side you'll have to generate an equivalent using https://github.com/Synergex/HarmonyCore/tree/master/Templates/TraditionalBridge/ODataModel.tpl & the ODataMetadata.tpl

We've got an example dispatcher for structure data https://github.com/Synergex/HarmonyCore/blob/master/TraditionalBridge.Test/Dispatcher/ArbitrarioDispatcher.dbl and the .net side https://github.com/Synergex/HarmonyCore/blob/master/HarmonyCore.Test/Bridge/BasicBridge.dbl https://github.com/Synergex/HarmonyCore/blob/master/Services.Controllers/OrdersMethods.dbl Specifically the ExternalCallContext parts in OrderMethods.dbl

This is all assuming when you ask about returning JSON that you just mean from traditional synergy -> .net code using traditional bridge. If that's not what you're asking then I have a totally different answer for you.

**Comment by Gl3nSt3wart** [comment]
Hi Jeff, Yes this answers my question. Thanks again. :)
