### ISSUE TITLE
CodeGen Create Models/Controllers from Repository Structure without file association

### ISSUE THREAD

**Issue by Gl3nSt3wart** [Synergex/HarmonyCore#125]
Hello,
I have a Structure that is used to read in data from a Relative file that is dynamically named. I am wondering if you have a method for using Codegen(or any other way) to create the POST/GET/ etc methods, Models, Controllers for this type of structure? 
I tried to switch the structure name in "set DATA_STRUCTURES= " in regen.bat but I get an error with this structure. The last one worked well, I assumed it was because there is no file associated with this one in repository(due to the dynamic name). Here is the error. 

<img width="315" alt="codegen_TXDATA_ERROR" src="https://user-images.githubusercontent.com/54644500/66479935-8416d580-ea6b-11e9-915b-fd829bb14380.PNG">

This would greatly speed up my code upgrade process and largely eliminate my need for traditional bridge use.

**Comment by SteveIves** [comment]
Any structures that you're going to generate code from for Harmony Core MUST have an associated file definition. What you're going to need to do is implement a custom FileChannelManager class in your Startup project. This class is responsible for opening new channels, and can be used to determine file names at run time.

Start by reading this and see if it gives you what you need: https://github.com/Synergex/HarmonyCore/wiki/Supporting-Multi-Tenancy

**Comment by Gl3nSt3wart** [comment]
Hi Steve, That looks like it will work. Thanks again!!
