### ISSUE TITLE
Changed Repository field now error with harmony core build

### ISSUE THREAD

**Issue by Gl3nSt3wart** [Synergex/HarmonyCore#145]
Hello,
I had to make a field name change in one of my repository tables as well as the link for an overlay. This was yesterday afternoon. This morning, I cant build the Harmony Core Project due to errors with 
GetPrototypes in TraditionalBridge for File Repository.synproj 
Funny thing is- the field I changed is only referenced as an class include of the table. I tried to output a new repository schema but same error. 
Any Ideas how to fix this?

![image](https://user-images.githubusercontent.com/54644500/70546889-0a1fcd00-1b3e-11ea-8fbf-22395c114ab0.png)

**Comment by hippiehunter** [comment]
that sounds like a visual studio/build system bug, its usually resolved by shutting down VS, and using task manager to kill any dotnet.exe processes or msbuild.exe processes that hang around. Internally there has been some work to mitigate this, but its still being tested.

**Comment by Gl3nSt3wart** [comment]
Hi Jeff,
              Thanks for your quick response. Yes it was a problem with Visual Studio 2019 again. It required a second reboot and an update to Version 16.4.1. I also had to make sure that my TraditionalBridge project was set to not Build in the solution properties. Now it seems to be running again. Sorry to bother you with Microsoft issues.

**Comment by Gl3nSt3wart** [comment]
Jeff was absolutely right! Thanks again. Not sure what happened....
