### ISSUE TITLE
Add support for PUT/PATCH/DELETE on alternate unique keys

### ISSUE THREAD

**Issue by hippiehunter** [Synergex/HarmonyCore#154]
using things like an autoseq key it would be good to support put/patch/delete operations even when its not the primary key.

- [x] Codegen Templates
- [x] EF Core provider support for auto seq keys?

Aha! Link: https://synergex.aha.io/features/HC-61

**Comment by hippiehunter** [comment]
Thinking about things a bit more, the driving force for this issue is to have support for auto seq keys. Because those are generated after storage, it shouldn't be possible to make a put endpoint that is based off auto seq. 

Patch should be doable for an autoseq or time created key, but would be difficult to use for a time modified key.

Delete should work for all unique keys

**Comment by SteveIves** [comment]
You're right, PUT to CREATE is not appropriate for auto-sequence keys, but PUT to update, or PATCH or DELETE should be supported.

There is also an argument to be made for allowing DELETE for non-unique keys. I think use cases are likely to be rare, but I'm sure there are some. I'm thinking this is something that would need to be explicitly enabled on a structure/key basis.

**Comment by hippiehunter** [comment]
This is fixed by 0babee9, There is a define that can be set `DEFINED_ENABLE_ALT_PATCH/DEFINED_ENABLE_ALT_PUT/DEFINED_ENABLE_ALT_DELETE`

It shouldn't be hard to enable non unique keys for delete if we choose to in the future

**Comment by SteveIves** [comment]
Oops, the Aha! integration clearly needs work! Re-Closing!
