### ISSUE TITLE
Solution created from harmonycore template fails to build due to bad path in repository project

### ISSUE THREAD

**Issue by mattl91** [Synergex/HarmonyCore#158]
Solution created from the harmonycore template fails to build due to bad path in repository project. Here's the error and the message that preceded the error:

C:\harmonycore\Hc0codegened\packages\Synergex.SynergyDE.Build.11.1.1020.2685\build\Synergex.SynergyDE.Repository.targets(538,3): warning MSB4011: "C:\Program Files\dotnet\sdk\3.1.100\NuGet.targets" cannot be imported again. It was already imported at "C:\Users\devadm.nuget\packages\synergex.synergyde.build\11.1.1000.2668-beta1\build\Synergex.SynergyDE.Repository.targets (538,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\harmonycore\Hc0codegened\Repository\Repository.synproj]

C:\harmonycore\Hc0codegened\packages\Synergex.SynergyDE.Build.11.1.1020.2685\build\Synergex.SynergyDE.Repository.targets(60,5): error MSB4062: The "SynergyTasks.ISMExtensioner" task could not be loaded from the assembly C:\harmonycore\Hc0codegened\packages\Synergex.SynergyDE.Build.11.1.1020.2685\build..\tools\dbl\SynergyTasks.Core.dll. Assembly with same name is already loaded Confirm that the declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\harmonycore\Hc0codegened\Repository\Repository.synproj]

Aha! Link: https://synergex.aha.io/features/HC-4

**Comment by SteveIves** [comment]
@mattl91, I can't repro this with the project templates that are currently on NuGet. Are you sure your project templates and SDI are both up to date?

**Comment by mattl91** [comment]
Yes, but perhaps something else is out of date. I'll look into this a bit more and get back to you.
