### ISSUE TITLE
Problem with multi-file $expand

### ISSUE THREAD

**Issue by SteveIves** [Synergex/HarmonyCore#163]
Using the standard Harmony Core demo environment, the following GET query fails:

https://harmonycoreapp.azurewebsites.net/odata/v1/Customers(8)?$select=CustomerNumber,Name&$expand=REL_Orders($select=OrderNumber,DateOrdered;$expand=REL_OrderItems($select=ItemNumber,ItemOrdered,QuantityOrdered,UnitPrice;$expand=REL_Item($select=CommonName,Size;$expand=REL_Vendor($select=Name))))

The issue is that the final $expand query `$expand=REL_Vendor($select=Name))))` is currently resulting in `REL_Vendor": null`

**Comment by hippiehunter** [comment]
this is fixed in d1a558d926d0b8aa0ec6be9050d50e39b9b75b32
