### ISSUE TITLE
$skip not working

### ISSUE THREAD

**Issue by nkim-radley** [Synergex/HarmonyCore#165]
Tried calling `$skip=5` and received the following error:

`System.ArgumentException: Expression of type 'System.Collections.Generic.IEnumerable`1[Services.Models.Customers]' cannot be used for parameter of type 'System.Linq.IOrderedEnumerable`1[Harmony.Core.DataObjectBase]' of method 'System.Linq.IOrderedEnumerable`1[Harmony.Core.DataObjectBase] ThenBy[DataObjectBase,String](System.Linq.IOrderedEnumerable`1[Harmony.Core.DataObjectBase], System.Func`2[Harmony.Core.DataObjectBase,System.String])' (Parameter 'arg0')`

**Comment by hippiehunter** [comment]
this looks like the same issue as #162, do you have an orderby in your query?

**Comment by nkim-radley** [comment]
It does look similar. And no, I do not have $orderby in my query.

**Comment by SteveIves** [comment]
We dealt with $skip recently: in #134

**Comment by hippiehunter** [comment]
@nkim-radley Is this issue solved for you?

**Comment by nkim-radley** [comment]
@hippiehunter Yes, it has been fixed with updates to HarmonyCore 3.1.75
