### ISSUE TITLE
$inlinecount support request

### ISSUE THREAD

**Issue by nkim-radley** [Synergex/HarmonyCore#166]
Front-end framework adds `$inlinecount` to Odata query by default (which the wiki lists as not available). Currently returns HTTP 500. It would be useful if this could be implemented for future use.

**Comment by SteveIves** [comment]
It looks like the $inlinecount option was present in OData 2 and OData 3, but was removed in OData 4. 

I see it documented in section 5.17 of the OData 3.0 URL conventions documentation (https://www.odata.org/documentation/odata-version-3-0/url-conventions/), but it is not mentioned at all in the OData 4.0 URL conventions documentation (http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html).

Harmony Core produces OData 4 services. Are you sure the front-end framework you mention is up to date and supports OData 4?

**Comment by nkim-radley** [comment]
We were able to up the version of OData that our front-end framework was using to 4.0 and it is now using $count. This can be closed.
