### ISSUE TITLE
Issue with sending filepath as parameter to Traditional Bridge

### ISSUE THREAD

**Issue by nkim-radley** [Synergex/HarmonyCore#185]
I found that my parameters that contain escaped backslashes "\\"  are getting cut off. For example...

`c:\\a\\b\\c`

... is getting passed as...

`\\c`

To note, our parameters can be optional and to my understanding this means they eventually get converted in some way. Any thoughts?

**Comment by hippiehunter** [comment]
is this for in, inout or out parameters?

**Comment by hippiehunter** [comment]
I have reproduced this for outbound parameters, but for me it looks like the data is making it to the traditional side ok.

**Comment by nkim-radley** [comment]
I'm seeing the opposite. My parameter is a required inout. When my method returns a parameter with `\`, I am seeing correctly escaped `\\`. However, when I pass my method `text1\\text2`, I get `\\text2` back.

**Comment by hippiehunter** [comment]
you're right, I did more digging last night and I think I've fixed it. Its in the Pre V11 Traditional Synergy Json parser. I'm just testing things now before I commit it.

**Comment by hippiehunter** [comment]
If you grab this updated Traditional Bridge file it should solve your issue. 
https://github.com/Synergex/HarmonyCore/blob/master/TraditionalBridge/Json.dbl

Let me know if it works for you.

**Comment by nkim-radley** [comment]
Updating Json.dbl seemed to do the trick. Thank you!

**Comment by SteveIves** [comment]
Resolved
