### ISSUE TITLE
Convert xfServerPlus Tests to Traditional Bridge

### ISSUE THREAD

**Issue by hippiehunter** [Synergex/HarmonyCore#201]
converting these tests will give us a high degree of coverage and confidence that existing projects can easily be transitioned.

Tests to convert:
- [x] Arbitrario
- [x] AutoTime
- [x] BinaryTransfer
- [x] data64k
- [x] Encrypt
- [x] IF913
- [x] LrgPkts
- [x] NoParams
- [x] Pool1
- [x] Pool2
- [x] Pool3
- [x] Pool4
- [x] Pool5
- [x] Pool6
- [x] smc
- [x] strtsts
- [x] syntst
- [x] TestDate
- [x] UserData
- [x] V93IF
- [x] WCFields
- [x] ZDateTime

**Comment by theplasmastorm** [comment]
Tests to convert:

- [x] Arbitrario
- [x] AutoTime
- [ ] BinaryTransfer
- [ ] data64k
- [x] Encrypt
- [x] IF913
- [ ] LrgPkts
- [x] NoParams
- [x] Pool1
- [x] Pool2
- [x] Pool3
- [x] Pool4
- [x] Pool5
- [x] Pool6
- [x] smc
- [ ] strtsts
- [x] syntst
- [x] TestDate
- [x] UserData
- [ ] V93IF
- [x] WCFields
- [x] ZDateTime
