### ISSUE TITLE
Unit Test: Fix tests that crash dbr.exe

### ISSUE THREAD

**Issue by theplasmastorm** [Synergex/HarmonyCore#209]
When ran, these tests crash dbr.exe via ntdll.dll.

Need to investigate why it crashes and fix it

Found in:
- [x] BinaryTransfer\getstructa
- [x] Encrypt\encrypt_tst4
- [x] smc\function_eight
- syntst ↓
- [x] msc_arytst_dec
- [x] msc_arytst_imp
- [x] msc_arytst_int
- [x] msc_arytst_str

**Comment by hippiehunter** [comment]
I just commited a project change to enable qstrict and fixed a bug in error handling for the unit test framework. These tests are now properly failing and let you know where. its always a wrong assumption about the size of a passed array from what i can tell.
