### ISSUE TITLE
Publish Issue

### ISSUE THREAD

**Issue by nkim-radley** [Synergex/HarmonyCore#234]
I was able to build and publish yesterday, but I am unable to publish today:

![image](https://user-images.githubusercontent.com/52933970/107396320-ab503d80-6acb-11eb-8878-366dcf33587f.png)

**Comment by hippiehunter** [comment]
does publish still work for tim? Whats changed since yesterday? Do you have any warnings when you build?

**Comment by nkim-radley** [comment]
I have not checked, but after our call I did the following:

- Get rid of space in Services.synproj
- Get rid of CodeDom in Services.Isolated.synproj
- Update Harmony Core

And I was able to build and publish yesterday, but now I am unable to.

Here is the entire output I am getting:

<pre>
C:\Users\[...]\Services.Controllers\Services.Controllers.synproj : warning NU1605: Detected package downgrade: System.Net.NameResolution from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different version.  [C:\Users\[...]\Services.Host\Services.Host.synproj]
C:\Users\[...]\Services.Controllers\Services.Controllers.synproj : warning NU1605:  Services.Controllers -> SSH.NET 2016.1.0 -> System.Net.Sockets 4.1.0 -> runtime.win.System.Net.Sockets 4.3.0 -> System.Net.NameResolution (>= 4.3.0)  [C:\Users\[...]\Services.Host\Services.Host.synproj]
C:\Users\[...]\Services.Controllers\Services.Controllers.synproj : warning NU1605:  Services.Controllers -> SSH.NET 2016.1.0 -> System.Net.NameResolution (>= 4.0.0) [C:\Users\[...]\Services.Host\Services.Host.synproj]
C:\Users\[...]\Services.Models\Services.Models.synproj : warning NU1605: Detected package downgrade: System.Net.NameResolution from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different version.  [C:\Users\[...]\Services.Host\Services.Host.synproj]
C:\Users\[...]\Services.Models\Services.Models.synproj : warning NU1605:  Services.Models -> Harmony.Core 3.1.323 -> SSH.NET 2016.1.0 -> System.Net.Sockets 4.1.0 -> runtime.win.System.Net.Sockets 4.3.0 -> System.Net.NameResolution (>= 4.3.0)  [C:\Users\[...]\Services.Host\Services.Host.synproj]
C:\Users\[...]\Services.Models\Services.Models.synproj : warning NU1605:  Services.Models -> Harmony.Core 3.1.323 -> SSH.NET 2016.1.0 -> System.Net.NameResolution (>= 4.0.0) [C:\Users\[...]\Services.Host\Services.Host.synproj]
C:\Users\[...]\Services.Isolated\Services.Isolated.synproj : warning NU1605: Detected package downgrade: System.Net.NameResolution from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different version.  [C:\Users\[...]\Services.Host\Services.Host.synproj]
C:\Users\[...]\Services.Isolated\Services.Isolated.synproj : warning NU1605:  Services.Isolated -> Services.Controllers -> SSH.NET 2016.1.0 -> System.Net.Sockets 4.1.0 -> runtime.win.System.Net.Sockets 4.3.0 -> System.Net.NameResolution (>= 4.3.0)  [C:\Users\[...]\Services.Host\Services.Host.synproj]
C:\Users\[...]\Services.Isolated\Services.Isolated.synproj : warning NU1605:  Services.Isolated -> Services.Controllers -> SSH.NET 2016.1.0 -> System.Net.NameResolution (>= 4.0.0) [C:\Users\[...]\Services.Host\Services.Host.synproj]
C:\Users\[...]\Services\Services.synproj : warning NU1605: Detected package downgrade: System.Net.NameResolution from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different version.  [C:\Users\[...]\Services.Host\Services.Host.synproj]
C:\Users\[...]\Services\Services.synproj : warning NU1605:  Services -> SSH.NET 2016.1.0 -> System.Net.Sockets 4.1.0 -> runtime.win.System.Net.Sockets 4.3.0 -> System.Net.NameResolution (>= 4.3.0)  [C:\Users\[...]\Services.Host\Services.Host.synproj]
C:\Users\[...]\Services\Services.synproj : warning NU1605:  Services -> SSH.NET 2016.1.0 -> System.Net.NameResolution (>= 4.0.0) [C:\Users\[...]\Services.Host\Services.Host.synproj]
C:\Users\[...]\Services.Isolated\Services.Isolated.synproj : warning NU1605: Detected package downgrade: System.Net.NameResolution from 4.3.0 to 4.0.0. Reference the package directly from the project to select a different version.  [C:\Users\[...]\Services.Host\Services.Host.synproj]
C:\Users\[...]\Services.Isolated\Services.Isolated.synproj : warning NU1605:  Services.Isolated -> Services.Models -> Harmony.Core 3.1.323 -> SSH.NET 2016.1.0 -> System.Net.Sockets 4.1.0 -> runtime.win.System.Net.Sockets 4.3.0 -> System.Net.NameResolution (>= 4.3.0)  [C:\Users\[...]\Services.Host\Services.Host.synproj]
C:\Users\[...]\Services.Isolated\Services.Isolated.synproj : warning NU1605:  Services.Isolated -> Services.Models -> Harmony.Core 3.1.323 -> SSH.NET 2016.1.0 -> System.Net.NameResolution (>= 4.0.0) [C:\Users\[...]\Services.Host\Services.Host.synproj]
  All projects are up-to-date for restore.
C:\Program Files\dotnet\sdk\3.1.405\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1047: Assets file 'C:\Users\[...]\Services.Host\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v3.1/win7-x64'. Ensure that restore has run and that you have included 'netcoreapp3.1' in the TargetFrameworks for your project. You may also need to include 'win7-x64' in your project's RuntimeIdentifiers. [C:\Users\[...]\Services.Host\Services.Host.synproj]
</pre>

**Comment by hippiehunter** [comment]
for testing sake, can you try installing the .net 5 sdk? It wont change the actual binaries that get deployed, but its what tim has on his machine and its what I use currently.

**Comment by hippiehunter** [comment]
additional thing to try, make sure SolutionDir is set to your solution folder path + a trailing slash. Then inside the Services.Host project folder, type dotnet build. Then go back out and run your publish

**Comment by nkim-radley** [comment]
At the moment, I'd prefer not to upgrade unless it is absolutely necessary. I also don't know how to set the SolutionDir. I looked it up and could not find where to set that within Visual Studio or set by CMD. How do I go about doing this?

It's weird because I can consistently re-clone my repository, build, then publish. However, if I try to delete the contents or the PUBLISH directory, or make a file change (e.g., RadleyServiceModels.dbl), then build, I get the error. Even after backing out my change, the publish error does not go away. Stashing my changes also does not fix the error. This seems consistent with the sudden issue with running publish from yesterday.

**Comment by hippiehunter** [comment]
SolutionDir is an Environment Variable used by the build system. Its currently set for you inside your publish.bat but you can also see it here https://github.com/Synergex/HarmonyCore/wiki/Publishing-in-IIS#example-publish-batch-file

when you say "build" are you typing dotnet build at a command prompt or are you pressing the build menu entry inside visual studio?

**Comment by nkim-radley** [comment]
I am running build from inside Visual Studio.

**Comment by hippiehunter** [comment]
can you set SolutionDir and run the build from the Services.Host folder

**Comment by nkim-radley** [comment]
I believe that fixed the issue. But, will I need to do this every time I want to build/publish?

**Comment by hippiehunter** [comment]
If it works consistently from a clean checkout and it works when you build from the command prompt, it sounds like a visual studio or possibly SDI related bug. We can just put 'dotnet build' into your publish.bat so it will do it automatically. Past that i can report it to the SDI team but they will need to be able to reproduce it and or run lots of diagnostics.
