### ISSUE TITLE
Support Harmony Core on Linux

### ISSUE THREAD

**Issue by SteveIves** [Synergex/HarmonyCore#237]
Synergex plans to add support for .NET 6 on Linux Servers. Once that capability is available, this is a general placeholder for any testing and work that may be required to be able to support Harmony Core services in that environment.

**Comment by hippiehunter** [comment]
Requirements for completion

- [ ] HarmonyCore.Test run in devops on linux as part of the automated pipeline
- [ ] Services.Test run in devops on linux as part of the automated pipeline
- [ ] Services.Test.CS run in devops on linux as part of the automated pipeline
- [ ] TraditionalBridge.UnitTest run in devops on linux as part of the automated pipeline
- [ ] #180 run on linux
- [ ] run [loadtest ](https://github.com/Synergex/LoadTestExample) on linux after upgrading to 6.0.x
