### ISSUE TITLE
OData route to get record by alternate key no longer generating if duplicates are not allowed

### ISSUE THREAD

**Issue by radanowak** [Synergex/HarmonyCore#256]
After updating Harmony Core from version 3.1.351 to 3.1.393 and running regen for our project, we noticed we lost some OData endpoints for retrieving a record by an alternate key.  The difference between the alternate keys for which endpoints generated and those that did not seemed to be whether the key was configured in RPS to allow duplicates.  It looks like the latest change to the /Templates/ODataController.tpl (commit ID 6f5d858708449727d5373945f37d50f5dc07d845) may align with this supposition.  The commit message seems to indicate the change was to filter out same-field-different-order keys, but our alternate keys do not always contain the same fields as the primary key.  Can this change be reviewed and/or explained in more detail?

**Comment by hippiehunter** [comment]
i'm looking into this, I think ALTERNATE_KEY_LOOP_UNIQUE is supposed to mean don't duplicate the loop output rather than anything to do with keys marked duplicates allowed. If keys being marked with duplicate is controlling behavior here there's either a misunderstanding on my part or just a codegen bug.

**Comment by radanowak** [comment]
Within the <ALTERNATE_KEY_LOOP> unique is an <IF DUPLICATES> for which the <ELSE> portion looks to have been removed.  This is what seemed to align with our thought but we're hoping to clarify.  Thank you for reviewing.

**Comment by hippiehunter** [comment]
can you replace that ALTERNATE_KEY_LOOP_UNIQUE section of the template with the contents from this gist and let me know how things go?

https://gist.github.com/hippiehunter/84f9a82ad04e6659d853220c1c916577

**Comment by radanowak** [comment]
Everything seems to check out.  The only other question I have is whether a similar change needs to be made or not to the ODataEdmBuilder template.  In revisiting the commit where the alternate key endpoints were lost in order to confirm this template change addresses our need, I noticed the "AddAlternateKeyAnnotation" calls were lost as well.

**Comment by hippiehunter** [comment]
I think this is fixed in 129ba5da48bb2f9e0e07f3e765a4bfe0a8531390, If it works for you i'll do a regular template release.

**Comment by radanowak** [comment]
With these changes, I am unable to build - I get an error for each controller that the SingleResult return value is inaccessible:

"Error DBL-E-ACCESS: %DBL-E-ACCESS, SingleResult is inaccessible : mreturn Ok(result.SingleResult())"

Something on my end?

**Comment by hippiehunter** [comment]
this should be solved with the latest cli tool/templates that were shipped

**Comment by radanowak** [comment]
Forgive me for the delay.  So grabbing the changes to the HarmonyCore.CliTool and Templates should suffice for resolving our build error?  Or are there other dependencies?  Just confirming there is no implication that we update to the latest release of Harmony Core.  We are currently at 3.1.416 if I'm not mistaken.  What's the latest version?

**Comment by hippiehunter** [comment]
3.1.459 is the latest but im not aware of anything you need in the newer versions. yeah latest templates should be all you need.
