### ISSUE TITLE
Missing Files in Build

### ISSUE THREAD

**Issue by nkim-radley** [Synergex/HarmonyCore#258]
There are at least two files that are no longer making it to the `/PUBLISH` directory. These files are the `launch.bat` and the `TraditionalBridgeHost.dbr`. When I looked at the `publish.bat`, I can see that those files are still meant to get copied to the dist directory, but they are missing their respective `/bin/../[dist]` directory.  Not getting a build error and the publish gives a warning that the aforementioned files cannot be copied to the dist (since they don't exist)

**Comment by hippiehunter** [comment]
We don't ship publish.bat, I think that either came from this documentation https://github.com/Synergex/HarmonyCore/wiki/Publishing-in-IIS#example-publish-batch-file or it was put there specially by @SteveIves. As we don't ship this file I think my recommendation is to just change publish.bat as you see fit.

**Comment by nkim-radley** [comment]
Are you saying that our publish.bat is out of date and that is why no `launch.bat` and `TraditionalBridgeHost.dbr` are getting created from the build?

**Comment by nkim-radley** [comment]
Files missing from TraditionalBridge build were in part due to `publish.bat` not running `msbuild` (therefore not building the non-.Net project).
Furthermore, issue with building TraditionalBridge seems to have been addressed in commit d20365ee5f0756d5e5629ae8ce8c63d614409559 (10.3.3g/pre Synergy v11 support).
