### ISSUE TITLE
Create tutorial to walk through improving a repository

### ISSUE THREAD

**Issue by hippiehunter** [Synergex/HarmonyCore#29]
For customers that use xfODBC today most of the structures/relations/keys should be good. However if they havent, then their repository will most likely have lots of missing or inaccurate information about relations, keys and files. We should create a tutorial to walk through solving the common problems that will be seen by customers in their real world repository files.

**Comment by SteveIves** [comment]
Repository setup guidelines are now provided [here](https://github.com/Synergex/HarmonyCore/wiki/Repository-Setup).
