### ISSUE TITLE
Return JSON objects from classic code to client

### ISSUE THREAD

**Issue by shiblydangdang** [Synergex/HarmonyCore#303]
I'm trying to return the following JSON directly from classic code back through HC to the client........

{
	"type": 1,
	"target": "getlists2_Result",
	"arguments": [{
		"return_status": 0,
		"jsonlist": [{
			"componentid": "co",
			"order": 1,
			"colour": 0,
			"userid": "TDE",
			"departmentid": "RME",
			"itemtype": "wflist",
			"listname": "7",
			"url": "/wfresults?list=COLLECTION&filter=BRD DEPOT",
			"icon": "bulletlist"
		}, {
			"componentid": "co",
			"order": 1,
			"colour": 0,
			"userid": "TDE",
			"departmentid": "RME",
			"itemtype": "wflist",
			"listname": "7",
			"url": "/wfresults?list=COLLECTION&filter=BRD DEPOT",
			"icon": "bulletlist"
		}]
	}]
}

...but I'm currently having to return it as an array of strings...

(I can't paste in here as it messes up the formatting)

...which I then convert to the correct JSON using this in aspHubCustoms.dbl...

	public class u11
		public componentid	,String
		public order		,int
		public colour		,int
		public userid		,String
		public departmentid	,String
		public itemtype		,String
		public listname		,String
		public url		,String
		public icon		,String
	endclass

	public partial class aspHub extends Hub<IaspHubClient>

		public async method getlists2, @Task
			aRequest, @asp.getlists_Request
		proc
			data resultstr,	string
			data callContext = ^as(Context.Items["RPCContext"], @aspService)
			data result = await callContext.getlists(aRequest)
			data getlists2_actualresult = new getlists2_Response() { jsonlist = new List<object>() }
			foreach resultstr in result.jsonlist
			begin
				getlists2_actualresult.jsonlist.add(JsonConvert.DeserializeObject<u11>(resultstr))
			end
			getlists2_actualresult.return_status=result.return_status
			await Clients.Caller.getlists2_Result(getlists2_actualresult)
		endmethod
	endclass

	public partial interface IaspHubClient			
		method getlists2_Result, @Task
			response, @getlists2_Response
		endmethod
   
	endinterface
	{JsonObject(MemberSerialization.OptIn)}
	public class getlists2_Response
		{JsonProperty}
		public return_status, int

		{JsonProperty}
		public jsonlist, @List<object>

	endclass

Notice the 

public jsonlist, List object parameter

This is my method definition...

	  <method name="getlists" id="getlists" routine="getlists_shim" elb="SHMLIB">
		  <param name="username" type="string" />
		  <param name="deptname" type="string" />
		  <param name="jsonresp" type="alpha" size="1000" dir="out"/>
		  <param name="jsonlist" type="string" size="0" dir="out" collection="System.ArrayList"/>
		  <param name="arraystructure" type="structure" structureName="Usrfav_rec" dim="1" dir="out"/>
		  <param name="arrayliststring" type="string" size="0" dir="out" collection="System.ArrayList"/>
		  <param name="arrayliststructure" type="structure" structureName="Usrfav_rec" dir="out" collection="System.ArrayList" size="220"/>
		  <param name="structurecollection" type="structure" structureName="Usrfav_rec" dir="out" collection="ArrayList" size="220"/>
		  <param name="return_status" type="decimal" size="1" dir="out"/>
		  <param name="return_message" type="alpha" size="500" dir="out"/>
	  </method>

I've added in the extra array options to see what happens and this is what is generated in aspServiceModels.dbl

      {JsonProperty}
        ;;; <summary>
        ;;; Parameter 4 (REQUIRED OUT @ArrayList)
        ;;; </summary>
        public jsonlist, [#]string

        {JsonProperty}
        ;;; <summary>
        ;;; Parameter 5 (REQUIRED OUT [*]USRFAV_REC)
        ;;; </summary>
        public arraystructure, [#]@UsrfavRec

        {JsonProperty}
        ;;; <summary>
        ;;; Parameter 6 (REQUIRED OUT @ArrayList)
        ;;; </summary>
        public arrayliststring, [#]string

        {JsonProperty}
        ;;; <summary>
        ;;; Parameter 7 (REQUIRED OUT @ArrayList)
        ;;; </summary>
        public arrayliststructure, [#]@UsrfavRec

        {JsonProperty}
        ;;; <summary>
        ;;; Parameter 8 (REQUIRED OUT D_HANDLE)
        ;;; </summary>
        public structurecollection, [#]@UsrfavRec

...the ones with UsrfavRec break the build.

Is it possible for the parameters in here to be created as a List of object as they are in TB/dispatchers/aspMethodDispatcher? 

If so, then I could add objects to the arraylist in classic code and it gets returned all the way back through to the client.

**Comment by shiblydangdang** [comment]
I've just realised that after adding this to the MDU.....

	  <param name="arrayliststructure" type="structure" structureName="Usrfav_rec" dir="out" collection="System.ArrayList" size="220"/>

...it created the Usrfav.dbl file in Service.Models but I didn't add it into the project! I've added this in now so the project builds again.

I'll see if I can add objects into this array now.

**Comment by hippiehunter** [comment]
To clarify, is the JSON you are trying to transmit typically stored in a hierarchical data structure, and does it have a fixed structure? If you encounter issues with your current approach due to the need to transmit nested variable-length data such as strings or lists, there are ways to perform fully custom serialization of objects.

**Comment by shiblydangdang** [comment]
Yes it's stored in a fixed structure.

**Comment by shiblydangdang** [comment]
I can't get a simple structure to return as an object and I will also need nested data later. Can you point me at some sample code to get this working please?

**Comment by hippiehunter** [comment]
Whats not working with your current attempt. Is it failing at runtime or compile time. Is the failure happening on the traditional side or the .Net side. Theres a logfile generated in the same folder as your .dbr. Depending on what kind of failure you're experiencing log files might be the right place to look. If the failure is making it to the .net side you should be seeing an exception in your attached visual studio debugger. I can usually get a pretty good feel for whats gone wrong just from the .Net side stack trace. 

If you're going to need to do nested/variable sized objects, I'd still like to diagnose whats gone wrong here first.

**Comment by shiblydangdang** [comment]
Totally agree. We should fix the simple option first. 

I'm just looking at versions now and it seems we are on 3.1.392!!! I guess this could be part of the problem so let me get up to date and see how it all looks after this.

**Comment by hippiehunter** [comment]
If you work where i think you do, I think you might have a branch in your git that is already 6.0.153 or 148

**Comment by shiblydangdang** [comment]
Unbelievable! It's funny how you know that's there but I don't!!

**Comment by hippiehunter** [comment]
that sounds like a likely name, but its more detail than I know.

**Comment by shiblydangdang** [comment]
Is anyone available to help me get this sorted please? I'm having a nightmare!

**Comment by hippiehunter** [comment]
I'm not sure what you're asking for, what the name of your git branch is? It sounded like HCUpgrade was a likely winner, is there something wrong with it?

**Comment by shiblydangdang** [comment]
I tried the HCUpgrade one but our code is out of date and it has build errors. 

I've managed to upgrade our master branch to latest HC but I'm still getting build issues. 

Not sure what the best approach is. Any thoughts?

**Comment by hippiehunter** [comment]
While I can help you with any specific build errors you send me, the upgrade from 3.x to 6.x is non trivial for *your* code. The generated bits of Harmony Core fully take care of themselves but any custom code may have references to namespaces or classes that Microsoft has removed between 3.x of aspnetcore and 6.x. I'm pretty sure that those problems have already been solved in your codebase (somewhere) so if something larger is still amiss you might want to wait for Dan to get back from vacation so he can give you a better lay of the land.

**Comment by shiblydangdang** [comment]
That makes sense thank you. I've made some progress now so I'll let you know how I get on. 

I'll create a brand new method to try out creating a json object in classic. Can you tell me what the parameter definition should be in mdu xml please for a structure?

**Comment by hippiehunter** [comment]
Isnt this xml you included earlier what you're looking for?
```
 <method name="getlists" id="getlists" routine="getlists_shim" elb="SHMLIB">
	  <param name="username" type="string" />
	  <param name="deptname" type="string" />
	  <param name="jsonresp" type="alpha" size="1000" dir="out"/>
	  <param name="jsonlist" type="string" size="0" dir="out" collection="System.ArrayList"/>
	  <param name="arraystructure" type="structure" structureName="Usrfav_rec" dim="1" dir="out"/>
	  <param name="arrayliststring" type="string" size="0" dir="out" collection="System.ArrayList"/>
	  <param name="arrayliststructure" type="structure" structureName="Usrfav_rec" dir="out" collection="System.ArrayList" size="220"/>
	  <param name="structurecollection" type="structure" structureName="Usrfav_rec" dir="out" collection="ArrayList" size="220"/>
	  <param name="return_status" type="decimal" size="1" dir="out"/>
	  <param name="return_message" type="alpha" size="500" dir="out"/>
  </method>
```

I don't normally write that xml manually. Generally I would either use the mdu (graphical utility) or dbl2xml with attributes directly in your code. That choice is sort of pre-determined based on how your org normally does development in this space.

https://www.synergex.com/docs/#xfnl/xfnlChap2Usingthemdutodefinesynergymethods.htm#DefiningParameters
https://www.synergex.com/docs/versions/v121/index.htm#xfnl/xfnlChap2Usingattributestodefinesynergymethods.htm

If you're asking how to define the structure part rather than the parameter part, that's probably in repository.

https://www.synergex.com/docs/versions/v121/index.htm#rps/Title_rps.htm

**Comment by shiblydangdang** [comment]
Sorry I'm not explaining particularly well.

I did generate that xml previously to see how it handled each type of parameter.

What I'm asking is, which is the best one to use?

**Comment by shiblydangdang** [comment]
Got a strange problem now after regen - in Services.Controllers\aspService.dbl it seems to be double line spacing so its coming out like this........

            ;;Make the JSON-RPC call the traditional Synergy routine
            data resultTuple = await CallMethod("user_priv"

            &   ,args.User_option

            &   ,ArgumentHelper.MayBeOptional(args.Special_priv)

            &   ,response.return_status

            &   )

and therefore won't build. If I remove the blank lines then it's fine. This wasn't a problem in 3.1 so is there something I've missed?

**Comment by hippiehunter** [comment]
i'm sort of shooting in the dark but is it possible you've run the harmony core upgrade from wsl instead of windows or alternatively run your git checkout from wsl instead of windows?

**Comment by shiblydangdang** [comment]
I just updated the nuget packages within visual studio until everything updated. Is there a better option?

**Comment by hippiehunter** [comment]
We have a dotnet-tool that manages these things for you to ensure you have templates and nuget packages that are tested to work together, it also does fixups where possible to smooth over upgrade incompatibilities. Here's the doc for it.

https://github.com/Synergex/HarmonyCore/wiki/Updating-Harmony-Core

**Comment by shiblydangdang** [comment]
Sorry I missed that in the wiki. Let me give that a go and see how I get on

Thanks

**Comment by shiblydangdang** [comment]
OK - I've followed the instructions and regen then tried to rebuild the solution but I'm getting this in several files.......

%DBL-E-IMPORT, Namespace Microsoft.AspNet.OData not found : import Microsoft.AspNet.OData
Services.Controllers
C:\Users\tony\source\repos\ForwardSolutions\Services.Controllers\AppShellUserPreferenceController.dbl
18

**Comment by shiblydangdang** [comment]
I found the nuget package to fix this but then there are lots more errors.

We aren't using odata currently so I'll turn it off in the regen.bat for now and see if that helps.

**Comment by hippiehunter** [comment]
that sounds like it should be a generated file, did it actually get generated though? check the timestamp. the imports for a generated controller should look pretty close to what you can see here this https://github.com/Synergex/HarmonyCore/blob/master/Services.Controllers/CustomersController.dbl.

If that isnt a generated file or its a no longer generated file you may want to either remove it from the solution or update the namespaces to the 6.x versions.

**Comment by hippiehunter** [comment]
There is not a nuget package to fix the error message you've shown here. The only package you might be seeing is the 3.x versions of something, you cannot mix and match 3.x and 6.x aspnetcore or odata packages

**Comment by shiblydangdang** [comment]
the files are being generated and I'm now getting an error in EdmBuilder.dbl........

import Microsoft.AspNet.OData.Builder

any ideas?

**Comment by hippiehunter** [comment]
What did you do to resolve your last error?

does your EdmBuilder.dbl look something like this template? https://github.com/Synergex/HarmonyCore/blob/master/Templates/ODataEdmBuilder.tpl

Often there is a split of generated and non generated code (in separate files using partial classes). I would only expect that error in non generated code or in code that had not yet been regenerated after the upgrade.

**Comment by shiblydangdang** [comment]
I removed the files and turned off the odata flag

I'm completely lost now - these files are being generated but then they won't build!

**Comment by shiblydangdang** [comment]
the templates look ok 

I've deleted the EdmBuilder.dbl now to see if it gets regenerated correctly.

**Comment by shiblydangdang** [comment]
that's regenerated now along with Startup.dbl - let's see if it builds

**Comment by hippiehunter** [comment]
I really dont think its productive to be turning features on or off when you're in the middle of trying to diagnose something. Please put that back.

**Comment by shiblydangdang** [comment]
so this is in the top of the edm template

import Harmony.Core
import Harmony.Core.Context
import Harmony.OData
import Microsoft.EntityFrameworkCore
import Microsoft.OData.Edm
import Microsoft.AspNetCore.Mvc
import System.Collections.Generic
import <MODELS_NAMESPACE>
import Microsoft.OData.ModelBuilder

but it generates this.....

import Harmony.Core
import Harmony.Core.Context
import Harmony.OData
import Microsoft.EntityFrameworkCore
import Microsoft.OData.Edm
import Microsoft.AspNet.OData.Builder
import Microsoft.AspNetCore.Mvc
import Microsoft.AspNetCore.Mvc.Versioning.Conventions
import System.Collections.Generic
import Services.Models

so then errors on 
import Microsoft.AspNet.OData.Builder
import Microsoft.AspNetCore.Mvc.Versioning.Conventions

**Comment by hippiehunter** [comment]
It sort of sounds like you might not be using the templates you think you are. What are the paths on disk for your regen.bat and the .tpl file you're expecting it to use.

**Comment by shiblydangdang** [comment]
I think you're right because if I manually fix the generated files to match the template then it builds ok.

How do I check where its lookin for templates? It looks like %SolutionDir%Templates which is correct

**Comment by hippiehunter** [comment]
can you paste the output from running 
`harmonycore upgrade-latest`

Also include the path to regen.bat and anything you're setting in your environment before running it.

**Comment by shiblydangdang** [comment]
C:\Users\tony\source\repos\ForwardSolutions>harmonycore upgrade-latest
This utility will make significant changes to projects and other source files in your Harmony Core development environment. Before running this tool we recommend checking the current state of your development environment into your source code repository, taking a backup copy of the environment if you don't use source code control.


Type YES to proceed:
YES
Checking for current version info
Scanning 'C:\Users\tony\source\repos\ForwardSolutions' for HarmonyCore project files
Using MSBuild from path: C:\Program Files\dotnet\sdk\6.0.405

Updating template files in C:\Users\tony\source\repos\ForwardSolutions\Templates
Found template files in C:\Users\tony\source\repos\ForwardSolutions\Templates\MySQL
Found template files in C:\Users\tony\source\repos\ForwardSolutions\Templates\SignalR
Found template files in C:\Users\tony\source\repos\ForwardSolutions\Templates\ReactRedux
Found template files in C:\Users\tony\source\repos\ForwardSolutions\Templates\TypeScript
Found template files in C:\Users\tony\source\repos\ForwardSolutions\Templates\TraditionalBridge
Updating traditional bridge files in C:\Users\tony\source\repos\ForwardSolutions\TraditionalBridge\source\bridge

**Comment by shiblydangdang** [comment]
C:\Users\tony\source\repos\ForwardSolutions\regen.bat

**Comment by shiblydangdang** [comment]
I'm not setting anything in the env

**Comment by shiblydangdang** [comment]
I've found the problem - its using the templates in the MySQL Sub directory!

**Comment by hippiehunter** [comment]
that's not something we ship so I don't think I can tell you what to do with it.

**Comment by shiblydangdang** [comment]
I can turn off mysql option for now so it doesn't use those templates

**Comment by hippiehunter** [comment]
I don't ship a mysql option so I don't know what turning it off is going to do. Turning options off with out knowing what the impact is sounds like a pretty surefire way to end up with a broken solution though.

**Comment by shiblydangdang** [comment]
I just want it to build - I will work out if its required once its building

**Comment by shiblydangdang** [comment]
we're using mysql for the backend database which is probably why this flag has been turned on in the past but HC should never access it directly so it shouldn't be required as far as I can see

**Comment by shiblydangdang** [comment]
its building now its using the correct templates - thanks for the pointer to that

**Comment by shiblydangdang** [comment]
could you confirm which of these I should use please?

	  <param name="arraystructure" type="structure" structureName="Usrfav_rec" dim="1" dir="out"/>
	  <param name="arrayliststring" type="string" size="0" dir="out" collection="System.ArrayList"/>
	  <param name="arrayliststructure" type="structure" structureName="Usrfav_rec" dir="out" collection="System.ArrayList" size="220"/>
	  <param name="structurecollection" type="structure" structureName="Usrfav_rec" dir="out" collection="ArrayList" size="220"/>

**Comment by hippiehunter** [comment]
The first one looks like a single element array. You would only use that if you want to return an array with a single Usrfav_rec. It doesn't sounds like you want that one.

The second one returns an arraylist of strings, If you're really trying to return arbitrary json that doesn't match up to the type system generally, that's the path of least resistance.

The third one will return a zero based arraylist of Usrfav_rec structures. If you're trying to return the contents of that particular structure this is probably the one you want. 

I'm a little fuzzy on the fourth one but i think it's just like the third one but, a one based ArrayList. System.Collections.ArrayList vs Synergex.SynergyDE.ArrayList. If I'm right, It's not likely you want this one.

In all of these cases the generated .Net client interface is going to return an array. So [#]string or [#]Usrfav_rec

**Comment by shiblydangdang** [comment]
thanks for the clarification.

if I use this one 
  <param name="arrayliststructure" type="structure" structureName="Usrfav_rec" dir="out" collection="System.ArrayList" size="220"/>
and get an array [#]Usrfav_rec will this convert to a list of json objects automatically or will it just return a long string representation of the record structure ie. a fixed length record like an isam record

**Comment by shiblydangdang** [comment]
I'll give it a try and see what happens then send some info if its not doing what I need

**Comment by shiblydangdang** [comment]
got a problem in regen.bat again now - because I turned off the MYSQL flag, it no longer creates the EdmBuilder.dbl or Startup.dbl as they are inside the check for the flag. Is this correct?

**Comment by shiblydangdang** [comment]
actually its the odata flag - so if I don't want odata I don't get edmbuilder or startup???

**Comment by hippiehunter** [comment]
The mechanism you're using to generate code only supports the same things that xfServerPlus supports. That's means the structures you're sending have to be fixed length. If you want to send arbitrary json you can send it using a string. Alternatively you can write your own DataObject serialize/deserialize method, I don't think I have a nice example for that though.

You don't want to turn off the odata flag, Its possible to deal with the fallout but I wouldn't do it unless you have some kind of hard blocker. The steps involved are way beyond a github issue.

**Comment by shiblydangdang** [comment]
ok makes sense. thanks for all your help

**Comment by danellis06460** [comment]
I have updated the branch HCupdate with the latest code from master so I believe this issue can be closed.

**Comment by shiblydangdang** [comment]
I still need to work out how json object is being passed back in our getcore function. I also then need to know if it's possible to pass back an array of json objects. I can see how you've converted from string array to json array but getcore seems to return json directly.

**Comment by shiblydangdang** [comment]
This is working for me now so I'll close the issue. Thanks for all your help.
