### ISSUE TITLE
The "Remove Structures" command causes GUI tool to crash 

### ISSUE THREAD

**Issue by mattl91** [Synergex/HarmonyCore#306]
Selecting "Remove Structures" in the Structures tab of the GUI tool causes the GUI tool to crash (i.e., disappear, bringing you back to the command line).

**To Reproduce**

1. Open the GUI tool for a solution with the sample data (e.g., the solution crated by https://github.com/Synergex/HarmonyCore/wiki/Tutorial-01-02-Creating-a-Demo-Service).
2. Click on the Structures tab
3. Select "Remove Structures", an option at the bottom of the screen.
4. Watch GUI tool disappear. You'll be back at the Windows command prompt.

**Expected behavior**
"Remove Structures" should probably open a window that would enable you to select structures and then select something like "OK" to instruct the GUI tool to remove the structures.

**Version**
 - harmony.core.clitool 6.0.158

**Comment by hippiehunter** [comment]
Fixed in #327
