### ISSUE TITLE
Token contents within StartupCustom.dbl

### ISSUE THREAD

**Issue by shiblydangdang** [Synergex/HarmonyCore#320]
Is it possible to access the contents of the Token within StartupCustom.dbl so that we can pass parameters to the launch script?

**Comment by SteveIves** [comment]
What token are you referring to? A JSON web token from request authorization? If so, I don't believe so, as tokens are associated with a specific request coming in to the service, after startup has completed.

**Comment by shiblydangdang** [comment]
Yeh sorry Steve that was a bit vague. Yes I mean jwt auth token. We're trying to associate the host.dbr with the client user if possible.

**Comment by SteveIves** [comment]
But the host DBR is pooled and shared/reused for multiple operations from multiple users. There is no one-to-one relationship to a user, unless you have disabled pooling, which would be really bad for performance.

**Comment by shiblydangdang** [comment]
Ah ok. Didn't realise that was the case. Thanks.

**Comment by SteveIves** [comment]
Actually, I was wrong; Dan just reminded me that in your environment, you do indeed have pooling turned off. I guess because of the requirement to maintain state in the back end for your multiple-call Signal-R workflows. I still don't think you can do what you are asking about in StartupCustom though, that's a one-shot deal and not involved on a call-by-call basis.

**Comment by shiblydangdang** [comment]
Ok no problem. Is the token not available before we do the ssh launch then?

**Comment by SteveIves** [comment]
I'm sure it is, but I don't think we currently have any extensibility points that would let you get at it and inject stuff (i.e. additional parameters) into the JSON-RPC messages. But if you were to add a parameter to send the username to your methods, you should be able to get to the token from say the aspService class, where the bridge calls are being invoked, and add some code to auto populate the parameter from the token.

**Comment by shiblydangdang** [comment]
Thanks for the info Steve. I should've probably explained what we're trying to do as you may know a better option. We seem to be ending up with lots of orphaned HOST.DBR sessions. The plan was to pass the client user to the the launch script so that we can do the following in launch.....

dbr HOST.DBR <tenant> <log> <user>

That way when checking processes on Linux we can see if it's certain users that are causing the problem and try and work out what's causing it.

**Comment by shiblydangdang** [comment]
You can ignore this now Steve as I've realised the log file has the process id in it's name - not sure why I didn't spot this previously. We can use this to find the user from the log file.
