### ISSUE TITLE
IIS data

### ISSUE THREAD

**Issue by SledgeEC** [Synergex/HarmonyCore#324]
I am having an issue retrieving the data when I publish to IIS on our client's server. I am able to retrieve a token but when I make a request the data is not being included. It seems as though the data is being cut-off.

I get a 200/ok response and the body starts normally but ends with the bracket in value, no ending brace or anything after [. It runs fine and returns the data when run in debug mode within VS.
  {
      "@odata.context": "https://...$metadata#recordname", 
      "value": [ 

Could this be an environment variable? I have tried setting the environment variables in the places suggested in the doc and by the people who have helped before but nothing seems to work.

My local machine did not have this issue, so maybe a setting in IIS is different on the server? I am setting up the site as described in the doc and the other settings do not stand out as being different than before.

Any thoughts on what I could be missing?

**Comment by SteveIves** [comment]
Yes, most likely a missing environment variable resulting in a file not found. That can cause this type of response. Turn on logging and check the log, you should see the error there. If you cant figure it out, hit me up during the day and I’ll try to help.

**Comment by SteveIves** [comment]
By the way, assuming your code base is reasonably up to date, which I think it is, a good place to set environment variables is in the appsettings file for your deployment environment. So if your deployment environment name is something like Production, you can set your environment variables in appsettings.Production.json, and they will be set in the host process by the Startup code.

{
  "AppSettings": {
    "Bridge": {
      "LogLevel": -1
    },
    "EnvironmentVariables": {
      "MT1": "F:\\PRODUCTION\\mt1",
      "PR1": "F:\\PRODUCTION\\pr1",
      "VD3": "F:\\PRODUCTION\\vd1",
      "VD5": "F:\\PRODUCTION\\vd1",
      "VD6": "F:\\PRODUCTION\\vd1",
      "WEBEXE": "C:\\inetpub\\ctracker.vdsc.com",
      "EXC": "C:\\inetpub\\ctracker.vdsc.com"
    }
  }
}

**Comment by tscaff** [comment]
Dovetailing into Steve's suggestion, you can also set your environment variables in the applicationHost.config file for IIS and it will be part of the application pool environment.  It's a little more work to set it, but if you have code that does something similar already, you can leverage that as well.  

Here is a small snipit of code to help in starting your research.

Example:

        public int SetWebAPIAppPoolEnv(ConfigurationData configData,string ServicePrefix)
        {
            string appPoolName = ServicePrefix + "." + configData.CustomerNumber;
            try
            {
                using (ServerManager serverManager = new ServerManager())
                {
                    Microsoft.Web.Administration.Configuration config = serverManager.GetApplicationHostConfiguration();
                    ConfigurationSection applicationPoolsSection = config.GetSection("system.applicationHost/applicationPools");
                    ConfigurationElementCollection applicationPoolsCollection = applicationPoolsSection.GetCollection();
                    ConfigurationElement addElement = FindElement(applicationPoolsCollection, "add", "name", appPoolName);
                    if (addElement == null)
                    {
                        return 1;
                    }

                    ConfigurationElementCollection environmentVariablesCollection = addElement.GetCollection("environmentVariables");

                    this.AddElement(configData, environmentVariablesCollection,"LOG",configData.InstallDir + "\\" + configData.BankID + "\\log");
                    serverManager.CommitChanges();
             }

Of course there is more code that this for removal and maintenance, but it's an option if you wish to undertake it.

**Comment by SledgeEC** [comment]
I turned logging back on but I do not see anything that is showing an error for the requests.

Here are the results I am getting from requesting a token and then the record. (I changed IP address to X.X.X.X)
2023-03-14 19:47:35 10.0.0.9 POST /Authentication/GetToken - 443 - X.X.X.X PostmanRuntime/7.31.1 - 200 0 0 227
2023-03-14 19:47:40 10.0.0.9 GET /odata/v1/Records $top=3 443 - X.X.X.X PostmanRuntime/7.31.1 - 200 0 0 1109

I initially was setting the variables in web.config but yesterday also added them to AppSettings and AppSettings.development. Some seem to be working, ie- the username and password from request are compared to environment variables before granting auth.

I am willing to try using that config file but am not familiar with what I would need to do there.

I don't know if this could be related but I also noticed that my token requests return a new token each time I make the request. I thought that subsequent requests normally returned the same token until it expired..?

**Comment by SteveIves** [comment]
So the stack trace you showed does indicate it's a file not found. Is FIL: the environment variable that you use to access your data files? Or are there others?

Setting EXEDIR and SFWINIPATH in there is also kind of weird, and I don't think will work, as the Synergy code is already running, so it's too late to set SFWINIPATH. I would remove those.

Otherwise, it looks like you're doing it right.

**Comment by SledgeEC** [comment]
Yes, FIL is the variable that points to my data files. I added the FIL, EXEDIR and SFWINIPATH when I tried deploying on the server and encountered this issue. I will remove the other two and leave FIL, try publishing fresh to see if that helps.

If the Synergy code is already running, is there a way to see what variables are present?

**Comment by SteveIves** [comment]
Not aware of anything to visualize a processes environment variables from the outside, but they should be there. Can you email me your Startup.dbl and Startup.Custom.dbl (if present)? There should be code in there to process the environment variables from the appsettings files. Also send me your appsettings*,json files.

**Comment by SteveIves** [comment]
Spoke too soon. Jeff reminded me that the SysInternals Process Explorer utility will allow you to view the environment of a process. Run it up, right-click on the process and pick Properties, then see the Environment tab.

https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer

**Comment by SledgeEC** [comment]
Okay, I will try that now. I also just sent the files directly to your e-mail.

**Comment by SledgeEC** [comment]
Got it working.

I was able to see with process explorer that SFWINI is pointing at a data directory on the server which appears to mimic the drives that contain the synergex versions we run on their system. After changing the environment variable to point to the FIL folder on that data drive, IIS is now returning the data as expected.

Thank you for your help as always. Sorry to be a burden, I am working through a lot of issues on my own but some of these I just can't figure out how to get through.

**Comment by SteveIves** [comment]
Not a burdon at all, happy to help, and happy you got it working.
