### ISSUE TITLE
Option to add interfaces is missing

### ISSUE THREAD

**Issue by mattl91** [Synergex/HarmonyCore#328]
**Describe the bug**
There's no "Add interfaces" option for the Interfaces tab for the CLI tool TUI, so there's no way to add interfaces.

**To Reproduce**
1. Open the GUI for the CLI tool.
2. Select the "Interfaces" tab.
3. Note that there's no "Add interfaces" option. 

**Expected behavior**
The "Structures" tab has an "Add structures" option that enables you to add data structures. The "Interfaces" tab should have something like that to add interfaces.

**CLI tool version**
 - 6.0.156

**Comment by hippiehunter** [comment]
closed by #335
