### ISSUE TITLE
Visual Studio nightmare!

### ISSUE THREAD

**Issue by shiblydangdang** [Synergex/HarmonyCore#343]
Does anyone have any tips for getting VS to be consistent with the HC solution?

We can build it one day no problem, then next day it fails with all sorts of different errors. Close and re-open VS a few times and it suddenly starts to build ok without us changing anything.

I also can't now open mdu or repository from VS - presume I have environment issues - any suggestions please? I get the warning with repos about making changes etc. I get the files don't exist for mdu.

VS 17.6.3
SDI 23.5.1212.0
SDE 12.1.1.3287

Thanks

**Comment by shiblydangdang** [comment]
Thanks for the info Dan but the actual mdu and repository programs don't even open so I can't do imports etc. I get the options on the Tools menu at the correct time but they don't open when clicked - I just get the messages about making changes etc. I'm sure it's something in my synergy env setup but no clue where to look.

**Comment by shiblydangdang** [comment]
I've  just installed SDE 3292 and it's asked me to reboot - I don't think it's asked me before so let's see if this tidies everything up!

**Comment by tscaff** [comment]
Yes, redefining RPS: on windows, very bad.

**Comment by shiblydangdang** [comment]
If I echo %RPS% then its just shows %RPS% - if I echo %DBLDIR% then its shows C:\Program Files\Synergex\SynergyDE\dbl\

Should RPS be set?

**Comment by tscaff** [comment]
No, I believe you should NOT have it defined at all.  Dan can confirm, but it has a very negative impact on the runtime especially in file channel situations, possibly others.

**Comment by danellis06460** [comment]
That looks ok, it should not be defined. Also check if you have a synergy.ini in play with synckini. If you open up a command prompt in visual studio see if you can dbr rps:rps and dbr dbldir:mdu  for clues. If not I am sure support can help you troubleshoot. As you suspect its probably something specfic to your environment because those things worked in your project on my laptop.

**Comment by tscaff** [comment]
One thing we did notice in our environments is that you cannot have a path to your source or other Synergy/DE resources such as repository or MDU that has a dash "-" in the path.  This will cause no end of problems for you.  If you have any path's with dashes in them, I highly suggested you remap your code and repository resources to remove any dashes from your paths.

**Comment by shiblydangdang** [comment]
ok so I had SFWINIPATH set - I've unset it and still not repos working - I might try removing all SDE/SDI and start again

**Comment by tscaff** [comment]
Have you configured any Environment Variables or Common Properties in your VS synproj yet?  One thing we found most helpful is to configure them in Common Properties.  Here is and example of some of our settings.  We made thing relative to our SolutionDir, but you may want to do something different.

![CommonProperties](https://github.com/Synergex/HarmonyCore/assets/87336986/bd746aa8-5deb-406e-89d2-515df3e91aba)

**Comment by shiblydangdang** [comment]
Right..... I re-installed everything and it all started working......but, I also commented out my SFWINIPATH in user EVs so wasn't sure which one fixed the problem! Put SFWINIPATH back in and repos and mdu stopped working again! Commented back out and all ok again. 

Thanks for your help gents and sorry for wasting so much time!
