### ISSUE TITLE
Synergy licenses

### ISSUE THREAD

**Issue by shiblydangdang** [Synergex/HarmonyCore#353]
Hi

Can someone please confirm what licenses are needed?

Do we need them for Harmony Core as well as run licenses for host.dbr?

Thanks

**Comment by shiblydangdang** [comment]
Should this question be sent directly to Synergex? I'm never 100% sure who covers what!

Thanks

**Comment by SteveIves** [comment]
Hi Tony,
Harmony Core services use Synergy Runtime licenses (DBR12 or DBS12), and as with xfServerPlus, there is a difference between license "requirement" (the number of licenses physically required to operate the service) and license "entitlement" (based on the number of users using the end application supported by the service).
For license requirement, you will need one license for the primary host process of the service (Services.Host), and if Traditional Bridge is used (as it is in your service) then you will also need one license for each Traditional Bridge host process (host.dbr). This number can vary based on the configuration of the service; it may be that there is only one host.dbr process running and handling all of the Traditional Bridge operations, or if the service gets busier, additional processes may be added to the pool, up to the maximum configured number of processes.
Regarding license entitlement, as with xfServerPlus, the number of licenses you are required to have to be compliant with your license agreement is based on the maximum number of physical users using the service at the busiest time.

**Comment by shiblydangdang** [comment]
Thanks Steve. Much appreciated.
