### ISSUE TITLE
Receive DBL-E-INVTYPSIZ error for memory handle or System.String argument for TraditionalBridge endpoint

### ISSUE THREAD

**Issue by radanowak** [Synergex/HarmonyCore#359]
We are looking to add a TraditionalBridge endpoint to our HarmonyCore project with an argument which can handle beyond the 64K limit of the alpha-type.  We have tried both the memory handle and System.String types, but when building after running regen.bat (to generate the code for the change to our MDU XML output file), we receive the following error in either case:

Error DBL-E-INVTYPSIZ: %DBL-E-INVTYPSIZ, Invalid data type/size specification {arg3} : arg3, a0

Our project currently targets Synergy version 10.3.3 but targeting version 11 did not make a difference in either case.

Let me know if I can provide any additional helpful information, and thanks in advance for assistance.

**Comment by hippiehunter** [comment]
The issue we're running into is that your Traditional bridge dispatchers are designed to allow optional parameters for backwards compatibility with your older xfNetlink COM API.  The COM API compatibility is limited to more or less support parameters of type a, d, i and some variants. If you're adding new endpoints we might want to consider adding a second interface that isnt set up for optional parameters, so we can dispatch strings/dynamic arrays/structures.

We might also want to set up a meeting to move your codebase forward a few versions.

**Comment by radanowak** [comment]
Makes perfect sense.  And yes, we were just discussing the need to get to current versions.  We'll be in touch!
