### ISSUE TITLE
Harmony core - traditional Bridge getting failed

### ISSUE THREAD

**Issue by GeethanjaliCP** [Synergex/HarmonyCore#360]
**Describe the bug**
We are trying to implement ‘Harmony core - Traditional Bridge’ for our project (AIS). We tried to add one of our modules to traditional bridge.
Note : We have that module in ELB, so we added the ELB (WPLIB) and AISSUB (common subroutine) as a reference to Traditional bridge folder.
No issues during compilation and when we try to debug the traditional bridge (by attaching the Synergy TELNET 4444 as debugging instance) we are getting the below message saying, “Testing traditional bridge configuration Failed.”
![image](https://git
![image](https://github.com/Synergex/HarmonyCore/assets/151000215/5e405cbe-a0dc-4fc5-a4bb-e7f6150d441e)
hub.com/Synergex/HarmonyCore/assets/151000215/d94c573f-5c82-413c-82ac-9f40a361aec3)
Synergy Version is 12.1.1.3278

How to replicate the issue:
1. On top of the latest Demo project we added elbs -> WPLIB(module which we trying to debug present here), AISSUB 9common subroutines needed for the module) and PDFSTUB (pdf related subroutines).
2.  We tried to add reference of the above ELB's in 'Traditional Bridge'.
3. when we try to attach an instance  for debug, application is entering in to 'Break mode' 
![image](https://github.com/Synergex/HarmonyCore/assets/151000215/6bfb032c-608c-4683-bce4-c9890e3455c0)
Then, by clicking on 'Continue' we are getting message as 'traditional bridge configuration failed'.
[Error_backtrace.txt](https://github.com/Synergex/HarmonyCore/files/14190357/Error_backtrace.txt)
4. When we look in to the VS instance where we tried to attach file, we can see below error as well:
<img width="445" alt="image" src="https://github.com/Synergex/HarmonyCore/assets/151000215/d10439dc-74ef-4f39-bf68-31d135a82571">

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser Chrome
 - Version [121.0.6167]

**Comment by GeethanjaliCP** [comment]
Attaching the Project structure as well for reference
![image](https://github.com/Synergex/HarmonyCore/assets/151000215/04e15701-cf3d-46d1-9264-e5219423999b)

**Comment by hippiehunter** [comment]
The error message in your screenshot is telling you that there is no AISSUB.ELB located in whatever folder EXEDIR is pointing to. There's a few options for why that might be. 

1. The AISSUB project isnt built yet. It's possible to run the .NET side without VS automatically building the traditional bridge project. 
2. The AISSUB project has its output set to somewhere other than EXEDIR
3. EXEDIR isnt set on the .NET side. If there isnt an EXEDIR environment variable set, The runtime will look for the AISSUB.ELB in the current working directory, likely the same folder as the .NET executable. You can configure environment variables in your debug launch configuration, prior to running the .NET EXE or in the appsettings.json file for your project. You can read more about this last option [here](https://github.com/Synergex/HarmonyCore/wiki/Environment-Variables)

I would start by figuring out where on disk AISSUB.ELB should be located and where it's currently located.

**Comment by GeethanjaliCP** [comment]
Thank you so much, ELB result was pointing to other directory so  we have made config changes to make sure ELB pointing to Traditional bridge directory (now both host.dbr and ELB are in same place) and that resolved the issue. And we were able to attach the process for debug as well.

**Comment by GeethanjaliCP** [comment]
This is resolved. closing this one.
