### ISSUE TITLE
Input Optional Parameter and Visual studio deposit values - traditional bridge.

### ISSUE THREAD

**Issue by GeethanjaliCP** [Synergex/HarmonyCore#361]
1.	Reg Optional parameter: 
We are trying to implement Traditional bridge and our Dibol programs have few parameters which are ‘Optional’. Currently in our application these optional parameters are handled easily (xcall ABC(param1,param2,param3**, ,** ,param6). When we are trying to implement with Harmony core, we have few observations:
1.	In Json request we don’t have any options to handle Optional parameters and it must be handled via code. Currently, when we send ‘NULL’ to one of the optional parameters it is throwing SYSTEM EXCEPTION. PFA file for exception stack trace:
 [Harmony.Core.Utility.BridgeException.txt](https://github.com/Synergex/HarmonyCore/files/14401120/Harmony.Core.Utility.BridgeException.txt)
2.	In our Dibol program, we have a check whether the parameter is passed or not, flow/logic of program runs based on this validation (%passed).
3.	We tried few things, PFB :
i) We enabled the ENABLE_BRIDGE_OPTIONAL_PARAMETERS in regen.BAT.
ii) we tried the solution provided in HC site (https://github.com/synergex/harmonycore/wiki/Tutorial-04-08-Add-Helper-Service-Class#optional-parameters).
Here in the site, we have example for output parameter(optional), and we tried to implement the same for input parameter(optional) (Added **?** at the end of variable) but no luck.
iii) We tried to do the code change in controller (BridgeMethodsService) as well like trying to call method with empty param or specifying NULL for optional param but we were getting error like ‘expecting more 
[Harmony.Core.Utility.BridgeException.txt](https://github.com/Synergex/HarmonyCore/files/14401115/Harmony.Core.Utility.BridgeException.txt)
Arguments’).
Kindly let us know.
2.	Deposit value to the variable in VS : 
When we attach the process to debug the traditional bridge programs and trying to deposit the variable values we are getting below errors:
“value could not be set please check your entry” : When we try to edit the variable in the ‘LOCALS’.
“unable to evaluate expression while editing value” : When we try to edit/deposit new value in the ‘Immediate Window’.
Do we have any config settings to be done to make the variables editable? Also this ‘EDIT variables’ function is working fine when we don’t attach the SYNERGY TELNET.

Kindly let us know.

**Comment by GeethanjaliCP** [comment]
<img width="673" alt="Mail_snapshot2024-02-26 073324" src="https://github.com/Synergex/HarmonyCore/assets/151000215/eac0caeb-2131-4457-8c46-c3949daab7c4">

**Comment by hippiehunter** [comment]
This might be a hard issue to solve over GitHub issues. There is some support for optional parameters in traditional bridge but it's probably not what you want. It exists as a compatibility bridge with xfnetlinkCOM and as a result, its missing quite a few features. 

I'm a little bit surprised by the exception message in your remote exception, it would be helpful to have the remote stack trace that you can get from that bridge exception object.

We may want to discuss at a slightly higher level, what your objective is with this endpoint. For example, you may want to consider writing a wrapper routine to help improve the ergonomics of your API surface rather than directly relying on optional parameters. 

As for your last question, I'm not certain from the context of the rest of your question if you're actually debugging the .net part or the traditional dbl part. We don't support setting values directly from the UI for traditional, but you can run commands from the immediate window as you've indicated.  I'm not sure you're using the right syntax for it as that looks like an error message coming from the .net debugger if you were to try to eval "myvar = 5”.  The traditional dbl debugger has different syntax for storing variables. I think the syntax if you're stopped in traditional dbl code is !deposit myvar=5 but that will only work if you're actually stopped in traditional dbl code.

**Comment by GeethanjaliCP** [comment]
Thank you for looking into it.
1. Visual Studio: Deposit option is working fine after using the correct syntax.
2. Reg Optional Parameter: 

Let me elaborate,

We are using traditional bridge and using the existing synergy programs. In the synergy program both optional parameters and required parameters are being used.

Consider a common scenario:

Adding student info and update student info:

Both adding the student info and update the student info **will call the same synergy program.**

Synergy program with parameters -> Param 1 - Student number, Param 2- student record (Name, class).
Now, when the user tries to create a NEW record, 'Student record' is needed and will be sent and Student number act as an optional. Whereas when we try to fetch student details based on student number then student record act as optional parameter.

JSON request payload in case of NEW request:
{
  "Student Number": Null,           ;To make this as optional Param.
  "Student_rec": {
       "Name":abc,
       "class":Higher
    }
  }

**In the above case, exception is raised. Please note that the param is declared as OPTIONAL in MDU and in dispatcher program we can see 'ArgumentHelper.arg1.MaybeOptional**


  Could you please let us know.

**Comment by GeethanjaliCP** [comment]
[BRIDGE_34640.LOG](https://github.com/Synergex/HarmonyCore/files/14449793/BRIDGE_34640.LOG)
Attached this file, please let me know if you expect some other files from us.

**Comment by GeethanjaliCP** [comment]
Hello... Any updates on this?

**Comment by hippiehunter** [comment]
Hi, sorry we had everyone from the services side of synergex out for meetings so it's been difficult to get an example for you between travel and meetings. It won't be tonight but I might have time tomorrow to show you what I mean when I say the right direction is to write wrapper functions that don't make use of optional parameters.

**Comment by hippiehunter** [comment]
```dbl

structure StudentStructure
    name, a40
    class, a10
endstructure

;;dont expose this, its a private implementation detail now
subroutine original_student_routine
	optional in student_id, d10
	optional inout student_data, StudentStructure
proc
	;; ... do something here probably
	;; if ^passed(student_id) then do something else do some other thing
endsubroutine


;;expose this routine with traditional bridge
subroutine get_student
	in student_id, d10
	;; I've guessed from your description that you mean to return student data
	;; when passing the id, if this isnt right adjust your parameters accordingly
	out student_data, StudentStructure
	record
		temp_student_data, StudentStructure
proc
	;;im using a temp here because technically if original_student_routine
	;;has a parameter that it reads from or writes to, it would be inout and
	;;the 'in' part of inout requires initialized data to be logically consistant
	xcall original_student_routine(student_id, temp_student_data)
	student_data = temp_student_data
endsubroutine

;;expose this routine with traditional bridge
subroutine update_student
	in student_data, StudentStructure
	record
		temp_student_data, StudentStructure
proc
	;;the student_data that i declared in the parameter above is 'in' but because
	;;im passing it to a routine parameter declared inout we're going to make a
	;;stopover in a temp variable
	temp_student_data = student_data
	;;notice im just putting this extra comma here to indicate that this isn't
	;;passing the first parameter
	xcall original_student_routine(, temp_student_data)
endsubroutine	
	
```

I've guessed a bit at what you're asking for but i think you can get the concept that I'm trying to get across. In terms of API design you will be much better off exposing functions that only support a single behavior. If the underlying functionality does 10 different things based on the passed parameters, make 10 descriptively named routines that take only the parameters needed to support their individual behavior. Each of those 10 descriptively named routines can just call the original routine under the hood, but this will let your API directly represent the operations you want to support.

**Comment by GeethanjaliCP** [comment]
Thank you so much Jeff for clear explanation.

Regards,
Geethanjali C.P

**Comment by GeethanjaliCP** [comment]
Thank you.. am closing this.
