### ISSUE TITLE
While using SignalR interface, getting exception during the actual call to the underlying traditional Synergy routine

### ISSUE THREAD

**Issue by GeethanjaliCP** [Synergex/HarmonyCore#364]
Hello Good day!!!

We are trying to use SignalR in our project. Facing exception during the actual call to the underlying traditional Synergy routine. PFA stack trace.
[SignalR_exception_traceback.txt](https://github.com/Synergex/HarmonyCore/files/14740089/SignalR_exception_traceback.txt)

Followed the below steps:
1. In MDU, have added interface name as 'SignalRAPI' and regenerated the code
2.  Added the 'SignalR' attribute in appsettings.Development.json and also added the 'External pool' code snippets for SignalR inside the 'startupcustom.dbl'.
3. Compiled and Build the solution.
4. when sending the request through 'Insomnia' getting exception in the below line, 
![image](https://github.com/Synergex/HarmonyCore/assets/151000215/e3b2cf8d-b3e5-4d6c-b54a-fdb08e6e7e8b)
![image](https://github.com/Synergex/HarmonyCore/assets/151000215/79746d6b-edbe-442f-beae-5543dd93d207)

not sure why the call is not happening, strange thing is while using the 'BridgeMethods' interface it is working fine but when i replace it with SignaR interface am seeing this exception.
Note: Attaching the BridgeMethods log as well for reference.
[BRIDGE_18452.LOG](https://github.com/Synergex/HarmonyCore/files/14740098/BRIDGE_18452.LOG)

Please do the needful. Thank you in Advance.

**Comment by danellis06460** [comment]
Have you tried testing it via Swagger ?

**Comment by GeethanjaliCP** [comment]
I tried to use swagger to check the signalR for the above method (Menu) but it gives us the below error:
![image](https://github.com/Synergex/HarmonyCore/assets/151000215/f944e9aa-e40a-4898-9455-731711c7ca30)
So, tried to test other module with SignalR using swagger, getting exception like below from swagger:
![image](https://github.com/Synergex/HarmonyCore/assets/151000215/69ee0077-98f0-4713-b5eb-aab600571313)
And exception happening near to the code:
![image](https://github.com/Synergex/HarmonyCore/assets/151000215/8dc272ab-e9be-48e9-b1c7-4915bfe918ca)

When we  change the 'PoolContextReuse' to 'False inside appsettings.Developement.JSON file, we are not seeing the exception. But when we try to attach the SynergyTELNET for debugging process, we need to attach it couple of times. (When trying to attach it first time and click on 'continue', it gets exited:
Started debugging runtime version 12.1.1 with debug revision 2
The program '[4444] localhost' has exited with code 4294967295 (0xffffffff).)
Then again we need to attach it. Is this fine? is there any other way?

**Comment by danellis06460** [comment]
I am not sure if poolcontextreuse would work in a signalr environment. I would only expect you to have to attach to the process once if you have specified visual studio debugging. It sounds like you are making progress now being able to make the signalr call successfully.

**Comment by GeethanjaliCP** [comment]
Hi,
We changed the settings of 'TestOnStartup' to 'FALSE' inside <appsettings.Development.JSON>. After this change we were able to attach the SynergyTelnet only once.
So, we assume when we use the SignalR -> TestOnStartup should also be set as False as like pool context reuse.

**Comment by GeethanjaliCP** [comment]
Closing this as we are not seeing any exception or error.
