### ISSUE TITLE
$expand returning incomplete "value" in response body

### ISSUE THREAD

**Issue by radanowak** [Synergex/HarmonyCore#372]
We have 2 structures - say A and B - where one is a child of the other (B a child of A).  Relations are defined in both directions on the same keys.  Our problem/question is that the key (and all keys for that matter) of structure B, the child, allows duplicates.  When we expand in either direction (As?$expand=REL_Bs -OR- Bs?$expand=REL_A), the response comes back successful (200 OK) but the "value" attribute in the response body comes back incomplete ... just the open square bracket:

"value": [

Is it invalid/unsupported to have a relation to a file without a unique key?  Or is this a bug or new scenario?

If I can provide any additional information or clarify anything further, just let me know.

Thanks in advance for any/all assistance.

**Comment by hippiehunter** [comment]
It sounds like there was an exception thrown in the middle of returning the data. Did anything get logged by the server?

**Comment by radanowak** [comment]
Yes, the log indicates the following:

System.ArgumentException: '[Key of B]' is not a member of type 'Services.Models.[B]' (Parameter 'propertyOrFieldName')
         at System.Linq.Expressions.Expression.PropertyOrField(Expression expression, String propertyOrFieldName)
         at ... 

I verified that the following section is only generated in the model by switching the key field we match on for the relation to not allow duplicates (which does not accurately reflect the key):

        .region "Properties to represent keys"
        
                ;;Access keys
        
        ...
        
        .endregion

Must we create a unique key to match on for the relation?  Or is there another way around it?

**Comment by hippiehunter** [comment]
Sorry for the delay, I was out on PTO. It does seem like there is a key definition problem but it's not clear to me what the definitions / keys involved are. Can you show me the key definitions in repository along with any relations.

**Comment by hippiehunter** [comment]
Can I have the two structure definitions and the relevant generated relation info from Services.Models\DBContext.dbl similar to this 
https://github.com/Synergex/HarmonyCore/blob/39742003533a3b2f65b0f5473997e34b0ef7c44b/Services.Models/DbContext.dbl#L185

including the comments that are generated above each of those calls. 

I'm starting to think that maybe one or more fields that is referenced in your key definition has been excluded from codegen for some reason.

**Comment by SteveIves** [comment]
Hey, Alex, I'm trying to load up your structures into a repository but I can't because of all the templates they reference. Any chance you can email me the whole schema, or if not, at least the template and file definitions associated with these structures?

**Comment by radanowak** [comment]
Sure thing - I'll send you an email.  Thanks in advance for your time/assistance, Steve!

**Comment by hippiehunter** [comment]
After a bit of digging, it's not possible to perform a join to a structure that has no unique keys. Looking at the fields in ca_ship_csn definition it seems like your primary key should actually be unique. The requirement to have at least one unique key exists to prevent errant duplicates showing up in your relations.

**Comment by radanowak** [comment]
Our primary key for the CASHIP_CSN is not unique because the serial field is not required and can/will be empty in some cases, in which another field in the file becomes the "unique" portion of the record ... but it can be any of the other fields, not a particular one or few.  So essentially, if we need a unique key on the file, it would be the entire record.  Thoughts/Suggestions?  Or no viable options?  As of now, we have a pretty big dependency on getting the join to work if at all possible.

**Comment by radanowak** [comment]
If it helps at all - it may not - this is something that came about as a result of our project upgrade earlier this year to the latest versions of HarmonyCore and its dependencies.  We were able to perform joins on a file with no unique keys prior to upgrading.

**Comment by hippiehunter** [comment]
I think we might be able fake in a key for your usecase. The caveat is that you might run into performance problems if you use this type in a large multi leg join.

**Comment by radanowak** [comment]
At this point, I think we may just go down the path of writing a program to achieve what we need and making a TraditionalBridge call to the new program rather than making an OData call.  Thanks for the time/assistance and I'll reach out if we need anything else.
