### ISSUE TITLE
Regarding imports for System.DirectoryServices.AccountManagement

### ISSUE THREAD

**Issue by tscaff** [Synergex/HarmonyCore#373]
I had a question about how to import and use the Active Directory Services classes from Microsoft for authenticating users to the domain.

I am trying to add these to our Services.Controller project, but I don't see the import being exposed, or a way to add assemblies to the project that would expose the classes that we would need.

Is there a way to get these imports into the project so we can utilize these assemblies for Active Directory operations?

**Comment by hippiehunter** [comment]
I'm not sure I understand the question. What is the nuget package you're trying to add?

**Comment by tscaff** [comment]
So as far as I know, this is not a nuget package, it's a Microsoft assembly that exposes classes to managing Active Directory accounts.  If they moved to a nuget package, I might have missed that.  Ultimately, like the other System. classes that are exposed in Synergy's HC, I wanted to use these classes to validate user account information is valid against the Active Directory.  

I don't know how to get this to import in these projects.  Do you have any guidance?

**Comment by hippiehunter** [comment]
That sounds like it might be a .NET Framework assembly rather than something that supports .NET 6/8.

**Comment by tscaff** [comment]
Closing question, as we will need a Nuget package to implement in .NET Core for Windows.
