### ISSUE TITLE
Version of .NET Core in Harmony Core

### ISSUE THREAD

**Issue by tscaff** [Synergex/HarmonyCore#374]
What version of .NET Core does the Harmony Core projects build against?   I feel like we are still building against .NET Core 6, but is there an effective way to tell, and how do we move up in versions if that is possible?

**Comment by tscaff** [comment]
Update, I do see in the Target Framework setting on the projects that we are current set to .NET 6.0.  Is Harmony Core forward compatible to where we can update this to 8.0 latest release version?

**Comment by hippiehunter** [comment]
You could probably do the upgrade to .NET 8 in your projects with the right jiggling of project files but EF Core 6 -> 8 has a few breaking changes that would prevent you from upgrading fully.

I've got a PR up for this #375 that I'm currently working on.

**Comment by tscaff** [comment]
Sounds good. I am going to close out this question but I am really anxious and excited to get #375 when you have it finished.
