### ISSUE TITLE
A Migration Path for xfServerPlus 

### ISSUE THREAD

**Issue by hippiehunter** [Synergex/HarmonyCore#84]
We have added initial support for generating the required wrappers and glue to allow existing xfServerPlus methods to be called using the JSON-RPC 2.0 protocol and the Traditional Bridge portion of Harmony Core. This needs to be extended to support all the data types and coercion that exist in the wild.

**Comment by theplasmastorm** [comment]
Will be added with https://github.com/Synergex/HarmonyCore/pull/218

**Comment by theplasmastorm** [comment]
#218 is merged in
